// Generated by IcedCoffeeScript 108.0.9
(function() {
  var employeeCtrl, pos;

  pos = angular.module('pos');

  employeeCtrl = function($scope, $http) {
    return extendScope($scope, $http, 'employee');
  };

  pos.controller("employeeCtrl", employeeCtrl);

}).call(this);
